### ISSUE TITLE
Remove milestones and generate changelog from commit diff

### ISSUE THREAD

**Issue by summerwollin** [grafana/grafana-build#303]
Kevin recently made a related [design doc](https://docs.google.com/document/d/1QSDnwh1AMO4D7OtbWkSY9i4UT5KFLAkiVXlFGY3mme4/edit#heading=h.v002lli9wzs0)
```[tasklist]
### Tasks
- [x] Try release-drafter (bad fit: only deals with Github Releases, not changelog.md)
- [x] Get list of PRs between two "commitish" items
- [x] Use graphQL instead of REST for higher rate limits
- [x] Extract correct author of the original commit
- [x] Extract labels from PR (changelog, bugfix, feature, plugin, ...)
- [x] Differentiate Enterprise PRs
- [x] Get proper PR title (without backported PR prefix) -- is regexp strip the only option? (yes)
- [x] How do we get previous tag for a given version (parse semver?)
- [x] dry-run option to print changelog markdown but create no PRs and don't publish a github release
- [x] we seem to have a bug with issues link in the changelogs? -> replace issues with pulls in the url
- [x] is date of the changelog always "today"? what is the source of truth there? (default: today, unless specified otherwise)
- [x] Publish markdown into a release draft
- [x] Fix: Version in the headline of a markdown should be without "v" prefix
- [x] Merge into grafana/grafana (instead of a sandbox)
- [x] Dry-run for the July release(s)
- [x] Publish markdown into a `CHANGELOG.md` PR
```

**Comment by baldm0mma** [comment]
Closed as finished.
